name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python tests/run_tests.py

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-test-report
          path: ci_reports/test_results.json
          if-no-files-found: warn

  report-tests:
    name: Report Tests Statuses
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: pr-test-report
          path: ci_reports

      - name: Render summary
        run: python scripts/report_tests.py
